language: python
python:
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"
install:
    - pip install -e .
    - pip install pytest
    - pip install hypothesis
script:
    - pytest --doctest-modules
cache: pip
